# (private) site default variables
class omd::site::params {

  $allowed_options =  ['ADMIN_MAIL', 'ALERTMANAGER', 'APACHE_MODE',
    'APACHE_TCP_ADDR', 'APACHE_TCP_PORT', 'AUTOSTART', 'BLACKBOX_EXPORTER',
    'CORE', 'CRONTAB', 'DATASCRYER', 'DEFAULT_GUI', 'DOKUWIKI_AUTH',
    'DOWNTIMEAPI', 'GRAFANA', 'GRAFANA_TCP_PORT', 'INFLUXDB', 'LIVESTATUS_TCP',
    'LIVESTATUS_TCP_PORT', 'MKEVENTD', 'MKEVENTD_SNMPTRAP', 'MKEVENTD_SYSLOG',
    'MKEVENTD_SYSLOG_TCP', 'MOD_GEARMAN', 'MULTISITE_AUTHORISATION',
    'MULTISITE_COOKIE_AUTH', 'MYSQL', 'NAGFLUX', 'NAGIOS_THEME', 'NAGVIS_URLS',
    'NSCA', 'PNP4NAGIOS', 'PROMETHEUS', 'PROMETHEUS_SNMP_EXPORTER',
    'PROMETHEUS_TCP_ADDR', 'PROMETHEUS_TCP_PORT', 'SNMPTRAPD', 'THRUK_COOKIE_AUTH',
    'TMPFS']
}
